
import {SCENARIOS,MEDICATIONS,STEP_NAMES} from './data.js';
import {createGameState,currentScenario,completeStep,submitMedication,submitDose,canAdminister} from './game-state.js';
let state=createGameState(), timerHandle;
const $=s=>document.querySelector(s), modal=$('#modal'), body=$('#modalBody');
const zones={monitor1:'34%',monitor2:'54%',monitor3:'73%',doctor:'88%',sink:'5%',cart:'18%',iv1:'29%',iv2:'49%',iv3:'68%'};
function patientZone(kind){return `${kind}${state.patientIndex+1}`}
function expectedZone(){if(state.step===1||state.step===10)return patientZone('monitor');if(state.step===9)return patientZone('iv');return ({2:'doctor',3:'cart',4:'sink',5:'cart',6:'cart',7:'cart',8:'cart',11:'sink',12:'cart'})[state.step]}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function render(){
 $('#score').textContent=state.score;$('#patients').textContent=state.completed;
 if(state.step<=12){const sc=currentScenario(state);$('#step').textContent=`${sc.id}｜步驟 ${state.step}/12`;$('#bar').style.width=`${((state.patientIndex*12+state.step-1)/36)*100}%`;$('#missionTitle').textContent=`目前任務：${STEP_NAMES[state.step-1]}`;$('#missionHint').textContent=`請前往：${zoneLabel(expectedZone())}`;}
 else{$('#step').textContent='任務完成';$('#bar').style.width='100%';$('#missionTitle').textContent='三位病人照護完成';$('#missionHint').textContent='查看學習成果';}
 $('#taskbar').innerHTML=STEP_NAMES.map((n,i)=>`<button class="task ${i+1<state.step?'done':''} ${i+1===state.step?'current':''}" data-step="${i+1}"><b>${i+1}</b><br>${n}</button>`).join('');
}
function zoneLabel(z){const n=state.patientIndex+1;if(z===`monitor${n}`)return `PACU-${n} 生理監視器側`;if(z===`iv${n}`)return `PACU-${n} 病人點滴側`;return ({doctor:'護理站醫師',cart:'電腦藥物車',sink:'洗手台'})[z]||'目前病人照護區'}
function move(zone){document.querySelectorAll('.move-marker').forEach(x=>x.remove());const marker=document.createElement('div');marker.className='move-marker';marker.style.left=zones[zone]||'12%';marker.textContent='▼ 主要護理師位置';$('#scene').appendChild(marker);if(state.step>12)return results();if(expectedZone()!==zone){toast(`目前步驟需前往「${zoneLabel(expectedZone())}」`);return;}setTimeout(()=>openStep(),350)}
document.querySelectorAll('.hotspot,.clinical-zone').forEach(b=>b.onclick=()=>move(b.dataset.zone));
function show(html){body.innerHTML=html;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function hide(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
$('#close').onclick=hide;
function advance(correct=true,msg='完成'){const r=completeStep(state,state.step,correct);hide();toast(`${msg}${r.points!==undefined?` +${r.points} 分`:''}`);render();if(state.step===13)setTimeout(results,500)}
function openStep(){const sc=currentScenario(state);const s=state.step;
 if(s===1)return assessment(sc);if(s===2)return isbar(sc);if(s===3)return order(sc);if(s===4||s===11)return handwash(s);
 if(s===5)return meds(sc);if(s===6)return dose(sc);if(s===7)return prep(sc);if(s===8)return doublecheck(sc);if(s===9)return administer(sc);if(s===10)return monitor(sc);if(s===12)return documentStep(sc);
}
function assessment(sc){show(`<h2>1. 評估病人｜${sc.id}</h2><div class="case"><b>${sc.patient}：</b>「${sc.complaint}」</div><div class="vitals">${sc.vitals.split(' · ').map(v=>`<span class="chip">${v}</span>`).join('')}</div><p>請完成必要評估：</p><div class="checks">${['意識狀態','生命徵象','疼痛／主要症狀','傷口／術後狀況'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">確認評估</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'評估完成');else $('#fb').innerHTML='<p class="danger">評估不完整：請完成意識、生命徵象、主要症狀與術後狀況評估。</p>'}}
function isbar(sc){show(`<h2>2. 告知醫師（ISBAR）</h2><div class="case">${sc.isbar}</div><div class="checks">${['I：自我介紹／病人身分','S：目前主要問題','B：手術與相關背景','A：目前評估與生命徵象','R：提出處置／評估建議'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">送出 ISBAR</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'ISBAR 通報完成');else $('#fb').innerHTML='<p class="danger">ISBAR 不完整：請依 I、S、B、A、R 順序完成通報。</p>'}}
function order(sc){show(`<h2>3. 核對醫囑</h2><div class="case"><b>醫囑：</b>${sc.order}</div><div class="checks">${['藥名','劑量','給藥途徑 IVP','給藥時間 STAT'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">完成核對</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'醫囑核對完成');else $('#fb').innerHTML='<p class="danger">醫囑核對不完整：需確認藥名、劑量、途徑及時間。</p>'}}
function handwash(step){show(`<h2>${step}. ${step===4?'第一次':'第二次'}洗手</h2><div class="case">依序完成手部衛生後再繼續。</div><button class="primary" id="ok">🫧 開始洗手</button><div id="wash"></div>`);$('#ok').onclick=()=>{let n=0;const d=$('#wash');const it=setInterval(()=>{n++;d.innerHTML=`<p>洗手進度 ${'●'.repeat(n)}${'○'.repeat(5-n)}</p>`;if(n===5){clearInterval(it);setTimeout(()=>advance(true,'手部衛生完成'),300)}},180)}}
function meds(sc){show(`<h2>5. 藥物櫃｜共 38 種藥物</h2><p>依醫囑選擇正確藥物。錯誤最多再給一次機會。</p><div class="medgrid">${MEDICATIONS.map((m,i)=>m.image?`<button class="medcard" data-id="${m.id}"><b class="mednum">${i+1}</b><img src="${m.image}" alt="${esc(m.name)}"><span>${esc(m.name)}</span></button>`:`<button class="medcard missing" data-id="${m.id}"><b class="mednum">${i+1}</b><div class="missing-photo">待補圖片</div><span>${esc(m.name)}</span></button>`).join('')}</div><div id="fb"></div>`);document.querySelectorAll('.medcard').forEach(b=>b.onclick=()=>{const r=submitMedication(state,b.dataset.id);if(r.status==='correct'){hide();toast('藥物辨識正確 +5 分');render()}else if(r.status==='retry'){$('#fb').innerHTML='<p class="danger">藥物選擇錯誤。請重新核對醫囑與藥物外觀；剩最後一次機會。</p>';b.disabled=true}else{$('#fb').innerHTML=`<p class="danger">第二次仍錯誤，本項 0 分。正確藥物：<b>${esc(r.answer)}</b></p><button class="primary" id="continue">繼續</button>`;$('#continue').onclick=()=>{hide();render()}}})}
function dose(sc){show(`<h2>6. 劑量計算</h2><div class="case"><b>醫囑：</b>${sc.order}<br><b>藥物規格：</b>${sc.drug}</div><div class="calc">醫囑劑量 ÷ 每 mL 含量 = 抽取量<br><input id="doseInput" type="number" step="0.1"> mL</div><button class="primary" id="ok">確認答案</button><div id="fb"></div>`);$('#ok').onclick=()=>{const r=submitDose(state,$('#doseInput').value);if(r.status==='correct'){hide();toast('劑量計算正確 +5 分');render()}else if(r.status==='retry'){$('#fb').innerHTML='<p class="danger">計算錯誤，請重新核對濃度與醫囑劑量；剩最後一次機會。</p>'}else{$('#fb').innerHTML=`<p class="danger">第二次仍錯誤，本項 0 分。正確抽取量：<b>${r.answer} mL</b></p><button class="primary" id="continue">繼續</button>`;$('#continue').onclick=()=>{hide();render()}}}}
function prep(sc){show(`<h2>7. 抽藥／準備藥物</h2><div class="case">${sc.drug}<br>目標抽取量：<b>${sc.correctVolume} mL</b></div><div class="calc">💉 請輸入實際抽取量 <input id="prep" type="number" step="0.1"> mL</div><button class="primary" id="ok">確認抽取量</button><div id="fb"></div>`);$('#ok').onclick=()=>{if(Math.abs(Number($('#prep').value)-sc.correctVolume)<.001)advance(true,'藥物準備完成');else $('#fb').innerHTML=`<p class="danger">抽取量與計算結果不一致。請重新確認，正確應為 ${sc.correctVolume} mL。</p>`}}
function doublecheck(sc){show(`<h2>8. 雙人核對｜電腦藥物車旁</h2><p>第二位護理師已到場 👩🏻‍⚕️ 👩🏻‍⚕️</p><div class="case"><b>${sc.id}</b>｜${sc.order}｜${sc.drug}｜抽取 ${sc.correctVolume} mL</div><div class="checks">${['病人身分','藥名','醫囑劑量','藥物濃度','計算後抽取量','給藥途徑 IVP','STAT 醫囑','藥物效期'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">確認完成雙人核對</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'雙人核對完成');else $('#fb').innerHTML='<p class="danger">安全核對尚未完成，無法進入給藥步驟。</p>'}}
function administer(sc){if(!canAdminister(state)){toast('⚠️ 尚未完成雙人核對，無法執行給藥');return}show(`<h2>9. 給藥｜病人點滴架側</h2><div class="case">${sc.order}<br>準備量：${sc.correctVolume} mL</div><div class="checks">${['再次確認病人身分','確認 IV 路徑通暢','核對藥物與醫囑','執行 IVP 給藥'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">完成給藥</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'安全給藥完成');else $('#fb').innerHTML='<p class="danger">給藥安全項目尚未完成。</p>'}}
function monitor(sc){show(`<h2>10. 給藥後監測｜監視器側</h2><div class="case"><b>治療反應：</b>${sc.monitor}</div><div class="checks">${['主要症狀／療效','意識狀態','BP／HR','RR／SpO₂','不良反應'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">確認監測</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'給藥後監測完成');else $('#fb').innerHTML='<p class="danger">監測不完整：請同時評估療效、生命徵象、意識與不良反應。</p>'}}
function documentStep(sc){show(`<h2>12. 完成紀錄</h2><div class="case"><b>${sc.id}</b><br>醫囑：${sc.order}<br>給藥量：${sc.correctVolume} mL<br>給藥後：${sc.monitor}</div><div class="checks">${['給藥時間','藥物名稱與劑量','給藥途徑','給藥原因','給藥後反應'].map(x=>`<label><input type="checkbox" class="need">${x}</label>`).join('')}</div><button class="primary" id="ok">送出紀錄</button><div id="fb"></div>`);$('#ok').onclick=()=>{if([...document.querySelectorAll('.need')].every(x=>x.checked))advance(true,'病人照護完成');else $('#fb').innerHTML='<p class="danger">紀錄不完整：請補齊給藥與療效紀錄。</p>'}}
function results(){show(`<h2>🏆 PACU Medication Mission 完成</h2><div class="result"><div><div class="scorebig">${state.score}<small>/100</small></div><p style="text-align:center">完成病人：${state.completed}/3</p></div><div><h3>學習回饋</h3><p>已完成三位病人的 12 步驟 PACU 給藥安全流程。</p><div class="errorlog">${state.errors.length?state.errors.map(e=>`<div>• ${esc(e)}</div>`).join(''):'本次無選藥／劑量計算錯誤。'}</div></div></div><button class="primary" id="again">重新挑戰</button>`);$('#again').onclick=resetGame}
function resetGame(){state=createGameState();hide();startTimer();render();toast('遊戲已重新開始')}
$('#reset').onclick=()=>{if(confirm('確定重新開始？目前進度將清除。'))resetGame()};
$('#help').onclick=()=>show(`<h2>📖 遊戲說明</h2><p>依上方「目前任務」提示，點擊場景中的正確位置讓護理師移動並完成操作。</p><p><b>12 步驟：</b>${STEP_NAMES.map((x,i)=>`${i+1}.${x}`).join(' → ')}</p><p>選藥與劑量計算各有兩次機會；未完成雙人核對不能給藥。</p>`);
function startTimer(){clearInterval(timerHandle);state.startedAt=Date.now();timerHandle=setInterval(()=>{const sec=Math.floor((Date.now()-state.startedAt)/1000);$('#timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`},1000)}
document.addEventListener('keydown',e=>{if(e.key==='Escape')hide()});
startTimer();render();
