import {PATIENTS,STEP_DEFINITIONS} from './data.js';import {state,activePatient,activeStep,completeStep,advance,renderGame,restartState} from './game.js';import {createMovementController} from './movement.js';import {taskMarkup,createRetryValidator} from './tasks.js';
const missions=document.querySelector('#missions');const icons=['📋','👨🏻‍⚕️','🧾','🧼','🖥️','🧮','💉','👩🏻‍⚕️👩🏻‍⚕️','💉','📈','📋','✅'];STEP_DEFINITIONS.forEach((s,i)=>{const b=document.createElement('button');b.className='mission';b.innerHTML=`<span class="icon">${icons[i]}</span>${i+1}<br>${s.label}`;b.onclick=()=>{if(i===state.stepIndex)document.querySelector('#hint').textContent=`目前任務：${s.label}，請前往正確互動區`;else showInfo(`<h2>第 ${i+1} 關：${s.label}</h2><p>這一關目前只能查看說明，不能提前執行或跳關。</p>`)};missions.appendChild(b)});
const player=document.querySelector('#player'),scene=document.querySelector('#scene');const mover=createMovementController({player,scene,onStateChange:p=>state.phase=p});let started=Date.now(),timer=setInterval(()=>{let s=Math.floor((Date.now()-started)/1000);document.querySelector('#time').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},1000);
function showInfo(html){document.querySelector('#dialogContent').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}document.querySelector('.x').onclick=()=>document.querySelector('#modal').classList.add('hidden');
function openActiveTask(){state.phase='TASK_OPEN';const p=activePatient(),step=activeStep().id;showInfo(taskMarkup(step,p));if(step===5){const v=createRetryValidator(p.med);document.querySelectorAll('[data-med]').forEach(b=>b.onclick=()=>handleRetry(v,b.dataset.med))}else if(step===6){const v=createRetryValidator(p.dose);document.querySelector('[data-dose]').onclick=()=>handleRetry(v,document.querySelector('#dose').value)}else document.querySelector('[data-answer]')?.addEventListener('click',finish)}
function handleRetry(v,val){const r=v.submit(val),f=document.querySelector('#feedback');if(r.status==='correct'){f.innerHTML='<p class="success">✓ 正確</p>';setTimeout(finish,350)}else if(r.status==='retry')f.innerHTML='<p class="error">答案不正確，還有最後一次機會。</p>';else if(r.status==='failed'){f.innerHTML='<p class="error">第二次仍不正確，系統已記錄錯誤並顯示正確答案。</p>';setTimeout(()=>finish(false),800)}}
function finish(correct=true){if(!completeStep({correct}))return;document.querySelector('#modal').classList.add('hidden');setTimeout(()=>{advance();renderGame();if(state.phase==='FINISHED')showInfo(`<h2>🎉 PACU Medication Mission 完成</h2><p style="font-size:28px"><b>${state.score}/100</b>｜完成病人 ${state.completedPatients}/3</p><p>三位病人的安全給藥流程均已完成。</p>`)},200)}
document.querySelectorAll('.interact').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();const target=el.dataset.target;if(target==='bed'&&Number(el.dataset.p)!==state.patientIndex){showInfo(`<h2>尚未開放</h2><p>請先完成 ${activePatient().id} 的 12 個步驟。</p>`);return}if(activeStep().target!==target && !(activeStep().target==='medcart'&&target==='computer')){document.querySelector('#hint').textContent=`目前是「${activeStep().label}」，這裡不是正確互動位置`;return}state.phase='TARGET_SELECTED';mover.walkToTarget(target,state.patientIndex,openActiveTask)}));
scene.addEventListener('click',e=>{if(e.target.closest('.interact'))return;const r=scene.getBoundingClientRect();mover.walkToPercent((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)});
document.querySelector('#restart').onclick=()=>{mover.cancelMovement();document.querySelector('#modal').classList.add('hidden');restartState();started=Date.now();player.style.left='43%';player.style.top='72%';renderGame()};document.querySelector('#help').onclick=()=>showInfo('<h2>🎮 遊戲說明</h2><p>點擊正確工作區後，主要護理師會先走到定位點，抵達後才會開啟任務。請依下方 12 關依序完成三位病人。其他關卡圖示可查看說明，但不能跳關。</p>');renderGame();
