import test from 'node:test'; import assert from 'node:assert/strict';
import { CASES } from '../domain/cases.js'; import { MEDICATIONS } from '../domain/medications.js'; import { createGame } from '../game/game.js'; import { targetForTask } from '../game/navigation.js';
test('12 scenarios map one-to-one to the 12 cabinet drugs and immutable image ids',()=>{assert.equal(CASES.length,12);assert.equal(MEDICATIONS.length,12);assert.deepEqual(new Set(CASES.map(c=>c.medicationId)),new Set(MEDICATIONS.map(m=>m.id))); for(const m of MEDICATIONS) assert.equal(m.image,`./assets/drug-${m.id}.png`)});
test('each game draws three distinct random scenarios',()=>{for(let i=0;i<50;i++){const g=createGame('practice');assert.equal(g.patients.length,3);assert.equal(new Set(g.patients.map(c=>c.id)).size,3)}});
test('assessment/monitor and administration use distinct bedside targets for each PACU bed',()=>{for(let i=0;i<3;i++){const assess=targetForTask('patient-bay','assess',i), admin=targetForTask('patient-bay','administer',i);assert.notDeepEqual(assess,admin);assert.ok(assess.x>admin.x)}});
import fs from 'node:fs';
test('v15 has exactly one nurse element and uses cleaned transparent nurse asset',()=>{const t=fs.readFileSync(new URL('../ui/templates-v13.js',import.meta.url),'utf8');assert.equal((t.match(/data-nurse/g)||[]).length,1);assert.match(t,/nurse-cartoon-v15\.png/)});
test('three PACU beds render three distinct patient head assets',()=>{const t=fs.readFileSync(new URL('../ui/templates-v13.js',import.meta.url),'utf8');assert.match(t,/patient-head-\$\{n\}\.svg/);for(let i=1;i<=3;i++)assert.ok(fs.existsSync(new URL(`../assets/patient-head-${i}.svg`,import.meta.url)))});
test('assessment complaint is bedside-only and removed before nurse moves',()=>{const a=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.match(a,/function removeComplaint/);assert.match(a,/if\(zone==='patient-bay'&&task==='assess'\)showComplaint/);assert.match(a,/function walkToZone\(zone\)\{removeComplaint\(\)/)});
