/* All 37 PACU drugs with real photos */
export const MEDICATIONS = [
  { id: 'morphine',        label: 'Morphine 10mg/mL/Amp',                     image: './assets/drugs/drug_01_morphine.png',        risk: 'high-alert' },
  { id: 'fentanyl',        label: 'Fentanyl 0.05mg/mL 2mL/Amp',              image: './assets/drugs/drug_02_fentanyl.png',        risk: 'high-alert' },
  { id: 'metoclopramide',  label: 'Chenday (Metoclopramide) 25mg/5mL/Amp',    image: './assets/drugs/drug_03_chenday.png',         risk: 'standard' },
  { id: 'imperan',         label: 'Imperan 10mg/2mL/Amp',                     image: './assets/drugs/drug_04_imperan.png',         risk: 'standard' },
  { id: 'atropine',        label: 'Atropine 1mg/mL/Amp',                      image: './assets/drugs/drug_05_atropine.png',        risk: 'emergency' },
  { id: 'nicardipine',     label: 'Zedipine (Nicardipine) 10mg/10mL/Amp',     image: './assets/drugs/drug_06_zedipine.png',        risk: 'high-alert' },
  { id: 'ephedrine',       label: 'Ephedrine 40mg/mL/Amp',                    image: './assets/drugs/drug_07_ephedrine.png',       risk: 'emergency' },
  { id: 'midazolam',       label: 'Midatin (Midazolam) 15mg/3mL/Amp',         image: './assets/drugs/drug_08_midatin.png',         risk: 'high-alert' },
  { id: 'norepinephrine',  label: 'Nobify (Norepinephrine) 4mg/4mL/Amp',      image: './assets/drugs/drug_09_nobify.png',          risk: 'high-alert' },
  { id: 'meperidine',      label: 'Pethidine HCl (Meperidine) 50mg/mL/Amp',   image: './assets/drugs/drug_10_pethidine.png',       risk: 'high-alert' },
  { id: 'dopamine',        label: 'Dopamin 200mg/5mL/Amp',                    image: './assets/drugs/drug_11_dopamin.png',         risk: 'high-alert' },
  { id: 'easydopa',        label: 'Easydopa 400mg/250mL/Bot',                 image: './assets/drugs/drug_12_easydopa.png',        risk: 'high-alert' },
  { id: 'agglutex',        label: 'Agglutex 25000 IU/5mL/Vial',              image: './assets/drugs/drug_13_agglutex.png',        risk: 'high-alert' },
  { id: 'fresofol',        label: 'Fresofol (Propofol) 200mg/20mL/Amp',       image: './assets/drugs/drug_14_fresofol.png',        risk: 'high-alert' },
  { id: 'epirenamin',      label: 'Epirenamin (Epinephrine) 1mg/1mL/Amp',     image: './assets/drugs/drug_15_epirenamin.png',      risk: 'emergency' },
  { id: 'adenocor',        label: 'Adenocor 6mg/2mL/Vial',                    image: './assets/drugs/drug_16_adenocor.png',        risk: 'emergency' },
  { id: 'sodium-bicarb',   label: 'Sodium Bicarbonate 20mL/Amp',              image: './assets/drugs/drug_17_sodium.png',          risk: 'emergency' },
  { id: 'voluven',         label: 'Voluven 6% 500mL/Bot',                     image: './assets/drugs/drug_18_voluven.jpeg',        risk: 'standard' },
  { id: 'vitagen',         label: 'Vitagen 50% 20mL/Amp',                     image: './assets/drugs/drug_19_vitagen.jpeg',        risk: 'standard' },
  { id: 'fursemide',       label: 'Fursemide 20mg/2mL/Amp',                   image: './assets/drugs/drug_20_fursemide.png',       risk: 'standard' },
  { id: 'calglon',         label: 'Calglon 10% 10mL/Amp',                     image: './assets/drugs/drug_21_calglon.jpeg',        risk: 'standard' },
  { id: 'dexamethasone',   label: 'Dexamethasone 5mg/mL/Amp',                 image: './assets/drugs/drug_22_dexamethasone.png',   risk: 'standard' },
  { id: 'diphenhydramine', label: 'Diphenhydramine HCL 30mg/Amp',             image: './assets/drugs/drug_23_diphenhydramine.png', risk: 'standard' },
  { id: 'dropedol',        label: 'Dropedol 2.5mg/mL 2mL/Amp',               image: './assets/drugs/drug_24_dropedol.png',        risk: 'standard' },
  { id: 'dupin',           label: 'Dupin 10mg/2mL/Amp',                       image: './assets/drugs/drug_25_dupin.png',           risk: 'standard' },
  { id: 'hydrocortisone',  label: 'HydroCortisone 100mg/Vial',               image: './assets/drugs/drug_26_hydrocortisone.png',  risk: 'standard' },
  { id: 'paindocine',      label: 'Paindocine (Ketorolac) 30mg/mL/Amp',       image: './assets/drugs/drug_27_paindocine.png',      risk: 'standard' },
  { id: 'nitrostat',       label: 'Nitrostat 0.6mg/Tab',                      image: './assets/drugs/drug_28_nitrostat.png',       risk: 'high-alert' },
  { id: 'nitroglycerin',   label: 'Mifiry (Nitroglycerin) 5mg/10mL/Amp',      image: './assets/drugs/drug_29_mifiry.png',          risk: 'high-alert' },
  { id: 'magnesium',       label: 'Magnesium sulfate 10% 20mL/Amp',           image: './assets/drugs/drug_30_magnesium.png',       risk: 'high-alert' },
  { id: 'novamin',         label: 'Novamin 5mg/mL/Amp',                       image: './assets/drugs/drug_31_novamin.png',         risk: 'standard' },
  { id: 'neostigmine',     label: 'Neostigmine 0.5mg/mL/Amp',                image: './assets/drugs/drug_32_neostigmine.png',     risk: 'standard' },
  { id: 'lidocaine',       label: 'Lidocaine 2% 100mg/5mL/Amp',              image: './assets/drugs/drug_33_lidocaine.png',       risk: 'standard' },
  { id: 'cordarone',       label: 'Cordarone 150mg/3mL/Amp',                  image: './assets/drugs/drug_34_cordarone.png',       risk: 'high-alert' },
  { id: 'saldolin',        label: 'Saldolin 5mg/2.5mL/Amp',                   image: './assets/drugs/drug_35_saldolin.png',        risk: 'standard' },
  { id: 'mannitol',        label: 'Mannitol 20% 100mL/Bot',                   image: './assets/drugs/drug_36_mannitol.png',        risk: 'standard' },
  { id: 'rocuronium',      label: 'Rocuronium 100mg/10mL/Vial',              image: './assets/drugs/drug_37_rocuronium.jpeg',     risk: 'high-alert' },
  /* TODO: labetalol 無實際藥物照片，cases.js SIM-04 使用此藥。需提供實際圖檔或替換情境藥物。 */
  { id: 'labetalol',       label: 'Labetalol 25mg/5mL/Amp',                  image: './assets/drugs/drug_placeholder.png',        risk: 'high-alert' },
]
