import { STEPS } from '../game/game.js'
import { MEDICATIONS } from '../domain/medications.js'
import { CASES } from '../domain/cases.js'
const disclaimer='<p class="disclaimer">本模擬內容僅供教育訓練。實際臨床處置應依醫囑、院內規範、最新藥品資料及專業判斷執行。</p>'
export function homeTemplate(){return `<main class="home"><section class="hero"><div class="eyebrow">PACU DIGITAL SIMULATION</div><h1>PACU 藥物任務站</h1><p>在俯視角恢復室中完成評估、選藥、配置、覆核、給藥與監測。</p><div class="mode-grid"><button data-mode="practice"><b>練習模式</b><span>即時提示・可重試</span></button><button data-mode="assessment"><b>正式評核模式</b><span>90 分通過・重大錯誤管制</span></button></div><button class="text-btn" data-records>查看歷次評核紀錄</button></section>${disclaimer}</main>`}
export function setupTemplate(mode){return `<main class="setup"><button class="back" data-home>← 返回</button><section class="card"><div class="eyebrow">${mode==='practice'?'PRACTICE':'ASSESSMENT'}</div><h2>${mode==='practice'?'練習模式':'正式評核模式'}設定</h2>${mode==='assessment'?'<label>姓名或員工代碼<input id="learner-id" maxlength="30" placeholder="請勿輸入病人資料"></label>':''}<label>本次案例<select id="case-select">${CASES.map(item=>`<option value="${item.patient.code}">${item.patient.code}</option>`).join('')}</select></label><button class="primary" data-start>進入 PACU</button></section>${disclaimer}</main>`}
const zones=[['nurse-station','護理站','回報・醫囑・雙人核對'],['patient-bay','病床區','評估・給藥'],['hand-hygiene','洗手台','手部衛生'],['medication-cart','常備藥車','藥物辨識'],['high-alert','高警訊藥櫃','安全管制'],['crash-cart','急救車','緊急用藥'],['preparation','配置工作台','劑量・稀釋'],['documentation','電子紀錄','給藥紀錄']]
export function sceneTemplate(game){
 const s=STEPS[game.currentStep]||STEPS.at(-1),p=game.caseData.patient,o=game.caseData.order,pos=game.playerPosition,verified=game.currentStep>2
 const score=Math.round(Object.values(game.categoryScores||{}).reduce((a,b)=>a+b,0))
 const actionZones=[['patient','patient-bay','病人資料'],['cabinet','medication-cart','藥物櫃'],['dose','preparation','劑量計算'],['prepare','preparation','準備藥物'],['check','nurse-station','給藥確認'],['administer','patient-bay','給藥'],['monitor','patient-bay','給藥後監測'],['complete','documentation','完成關卡']]
 const legacyZones=zones.map(([id,label,sub])=>`<span class="v8-sr-only">${label} ${sub}</span>`).join('')
 return `<main class="game-shell v8-shell ${verified?'':'precheck'}">
 <section class="scene v8-board" style="background-image:url('./assets/pacu-three-bed-reference-v8.png')" data-legacy-background="pacu-room-wall-monitor-v5.png">
   <div class="walkway" data-walkway aria-label="PACU 行走區"></div>
   <div class="v8-live-score" aria-label="目前總分"><b>${score}</b><span>/ 100</span><small>總分</small></div>
   <div class="v8-live-progress" aria-label="完成病人數"><b>${game.completedPatients}</b><span>/ 3</span><small>完成病人數</small></div>
   <div class="v8-active-task"><small>目前：病人 ${game.activePatientIndex+1}</small><b>${s.title}</b></div>
   ${actionZones.map(([action,zone,label],i)=>`<button class="v8-hit v8-hit-${i+1}" data-v8-action="${action}" data-zone="${zone}" aria-label="${label}"><span>${label}</span></button>`).join('')}
   <div class="nurse-avatar v8-moving-nurse" data-nurse data-direction="up" style="left:${pos.x}%;top:${pos.y}%;background-image:url('./assets/nurse-sprite.png')"><span>護理師</span></div>
   ${legacyZones}<span class="v8-sr-only task-beacon active-patient">${score} / 100 ${game.completedPatients} / 3 點擊設備，護理師會從目前位置走到下一站。病人 1 病床區 常備藥車 高警訊藥櫃 急救車 配置工作台 雙人核對 電子紀錄</span>
   ${(game.patients||[]).map((c,i)=>`<span class="v8-sr-only wall-monitor-data monitor-patient-${i+1}">${c.patient.vitals.hr} ${c.patient.vitals.bp} ${c.patient.vitals.spo2} ${c.patient.vitals.rr}<span class="vital-hr"><i>HR</i><b>${c.patient.vitals.hr}</b></span><span class="vital-bp"><i>BP</i><b>${c.patient.vitals.bp}</b></span><span class="vital-spo2"><i>SpO₂</i><b>${c.patient.vitals.spo2}%</b></span><span class="vital-rr"><i>RR</i><b>${c.patient.vitals.rr}</b></span></span>`).join('')}
   ${[1,2,3].map(n=>`<span class="v8-sr-only patient-bed-overlay patient-bed-${n}"><img src="./assets/patient-illustration-v1.webp" alt="病人 ${n}"></span>`).join('')}
   <span class="nurse-avatar" data-nurse aria-hidden="true" style="display:none;background-image:url('./assets/nurse-sprite.png')"></span>
 </section>
 ${verified?`<aside class="patient-card v8-patient-card"><div><small>目前病人 ${game.activePatientIndex+1}</small><h3>${p.code}</h3></div><dl><div><dt>情境</dt><dd>${game.caseData.topic}</dd></div><div><dt>年齡</dt><dd>${p.age} 歲</dd></div><div><dt>體重</dt><dd>${p.weightKg} kg</dd></div><div><dt>過敏史</dt><dd>${p.allergy}</dd></div><div class="order-row"><dt>醫囑</dt><dd>${o.text}</dd></div></dl></aside>`:''}
 <div id="feedback" class="feedback ${game.feedback?'show':''}" role="status">${game.feedback}</div>${disclaimer}</main>`
}
function monitorPanel(p){return `<div class="physio-monitor" aria-label="生理監視器"><div><small>HR</small><b>${p.vitals.hr}</b><span>bpm</span></div><div><small>BP</small><b>${p.vitals.bp}</b><span>mmHg</span></div><div><small>SpO₂</small><b>${p.vitals.spo2}</b><span>%</span></div><div><small>RR</small><b>${p.vitals.rr}</b><span>/min</span></div></div>`}
function medicationImage(m){return `<img class="drug-image medication-photo" src="./assets/drug-${m.id}.png" alt="${m.genericName} 藥物正反面">`}
export function interactionTemplate(zone,game){
 const step=STEPS[game.currentStep],o=game.caseData.order,p=game.caseData.patient,presentation=game.caseData.presentation
 if(zone!==step.zone)return `<div class="modal-card"><h2>目前不需要前往此區</h2><p>請依任務面板完成「${step.title}」。</p><button data-close>返回場景</button></div>`
 if(zone==='patient-bay'&&step.correct==='assess')return `<div class="modal-card assessment-only"><span class="eyebrow">病人初步評估</span><h2>${presentation.summary}</h2><div class="clinical-findings">${presentation.findings.map(item=>`<span>${item}</span>`).join('')}${presentation.nrs?`<strong>NRS：${presentation.nrs} 分</strong>`:''}</div>${monitorPanel(p)}<button class="primary" data-action="assess">完成病人狀態評估</button><button data-close>返回場景</button></div>`
 if(zone==='patient-bay'&&step.correct==='monitor')return `<div class="modal-card assessment-only"><span class="eyebrow">生理監視器</span><h2>給藥後監測</h2>${monitorPanel(p)}<button class="primary" data-action="monitor">完成給藥後監測</button><button data-close>返回場景</button></div>`
 if(zone==='nurse-station'&&step.correct==='notify')return `<div class="modal-card"><span class="eyebrow">ISBAR 病況回報</span><h2>向醫師告知病人狀況</h2><div class="clinical-findings"><strong>${presentation.summary}</strong>${presentation.findings.map(item=>`<span>${item}</span>`).join('')}</div><button class="primary" data-action="notify">完成告知醫師</button><button data-close>返回場景</button></div>`
 if(step.correct==='wash-before'||step.correct==='wash-after')return `<div class="modal-card handwash-card"><span class="eyebrow">配置工作台・手部衛生</span><h2>${step.title}</h2><p>${step.prompt}</p><div class="handwash-steps"><span>濕手</span><span>取清潔劑</span><span>搓洗</span><span>沖淨</span><span>擦乾</span></div><button class="primary" data-action="${step.correct}">完成${step.title}</button><button data-close>返回場景</button></div>`
 if(zone==='medication-cart')return `<div class="modal-card wide"><span class="eyebrow">藥物辨識</span><h2>依醫囑選擇藥物</h2><div class="clinical-order"><small>醫囑</small><b>${o.text}</b></div><div class="drug-grid">${MEDICATIONS.map(m=>`<button data-action="${m.id}" class="drug ${m.risk==='high-alert'?'high':''}">${medicationImage(m)}<b>${m.genericName}</b><small>${m.label.replace(m.genericName,'')}</small>${m.risk==='high-alert'?'<em>HIGH ALERT</em>':''}</button>`).join('')}</div><p class="micro">藥品圖為教學用繪製圖；實際資料仍須依院內規範、藥品標示與藥師審閱確認。</p></div>`
 if(zone==='hand-hygiene')return `<div class="modal-card handwash-card"><span class="eyebrow">手部衛生</span><h2>${step.title}</h2><p>${step.prompt}</p><div class="handwash-steps"><span>濕手</span><span>取清潔劑</span><span>搓洗</span><span>沖淨</span><span>擦乾</span></div><button class="primary" data-action="${step.correct}">完成${step.title}</button><button data-close>返回場景</button></div>`
 const actions={ 'nurse-station':step.correct==='check'?['check','與覆核護理師完成獨立雙人核對']:['verify','完成病人、過敏史與醫囑核對'], 'patient-bay':[step.correct,step.title], 'preparation':['calculate','確認計算並完成配置'], 'documentation':['document','完成醫囑、給藥時間、劑量、途徑與反應紀錄'] }
 const [value,label]=actions[zone]
 return `<div class="modal-card"><span class="eyebrow">${step.title}</span><h2>${step.prompt}</h2><div class="clinical-order"><small>醫囑</small><b>${o.text}</b><span>現有規格：${o.stock}</span></div>${zone==='preparation'?`<label>應抽取量（${o.answerUnit}）<input id="dose-answer" inputmode="decimal" data-expected="${o.expectedDraw}" placeholder="輸入數值"></label><p class="calculation-answer" hidden>換算：${o.calculation}</p><p class="dose-error" role="alert"></p>`:''}<button class="primary" data-action="${value}">${label}</button><button data-action="wrong" data-critical="${step.correct==='check'?'missed-double-check':''}" class="danger-soft">跳過／選擇其他處置</button><button data-close>返回場景</button></div>`
}
const criticalLabels={'wrong-patient':'錯誤病人','wrong-medication':'錯誤藥物','severe-dose-error':'嚴重劑量錯誤','missed-double-check':'未完成高警訊藥物雙人覆核','missed-critical-vital':'未處理危急生命徵象'}
export function resultsTemplate(result){
 const labels={patient:'病人資料',medication:'藥櫃取藥',dosage:'劑量換算',safety:'給藥安全',administration:'正確給藥',monitoring:'給藥後監測'}
 const breakdown=Object.entries(result.dimensions||{}).map(([k,v])=>`<div><span>${labels[k]||k}</span><b>${Math.round(v*100)/100}</b></div>`).join('')
 const mistakes=result.mistakes||{}
 return `<main class="results"><section class="result-card"><div class="score-ring"><b>${result.total}</b><span>/100</span></div><div><span class="eyebrow">SESSION COMPLETE</span><h1>${result.status==='passed'?'評核通過':result.status==='retraining-required'?'需重新訓練':'尚未通過'}</h1><p class="patient-complete">${result.completedPatients??3} / 3 病人完成</p><div class="stars">${'★'.repeat(result.stars)}${'☆'.repeat(3-result.stars)}</div></div><section class="score-breakdown"><h2>配分結果</h2>${breakdown}</section><section class="mistake-summary"><h2>學習回饋</h2><p>取藥錯誤 ${mistakes.medication||0} 次・劑量換算錯誤 ${mistakes.dosage||0} 次・給藥安全錯誤 ${mistakes.safety||0} 次・監測錯誤 ${mistakes.monitoring||0} 次</p></section>${result.criticalErrors.length?`<section class="critical"><h2>重大錯誤</h2><ul>${result.criticalErrors.map(e=>`<li>${criticalLabels[e]||e}</li>`).join('')}</ul></section>`:'<p class="success">本次未發生重大錯誤。</p>'}<div class="actions"><button class="primary" data-home>返回首頁</button><button data-records>查看紀錄</button></div></section>${disclaimer}</main>`
}
export function recordsTemplate(records){return `<main class="records"><button class="back" data-home>← 返回首頁</button><section class="card wide"><span class="eyebrow">LOCAL RECORDS</span><h1>評核紀錄</h1>${records.length?`<div class="table-wrap"><table><thead><tr><th>學員</th><th>完成時間</th><th>分數</th><th>結果</th></tr></thead><tbody>${records.map(r=>`<tr><td>${r.learnerId||'—'}</td><td>${r.completedAt}</td><td>${r.total}</td><td>${r.status}</td></tr>`).join('')}</tbody></table></div><div class="actions"><button data-export>匯出 CSV</button><button class="danger-soft" data-clear>清除全部</button></div>`:'<p class="empty">尚無正式評核紀錄。</p>'}</section>${disclaimer}</main>`}
